settings:
  username: "0bVdnt"
  max_lines: 5
  readme_file: "./README.md"
  commit_msg: "chore: update recent activity"

  disabled_events:
    - push

messages:
  starred_repo: "⭐ Starred {URL}"
  forked_repo: "🍴 Forked {URL}"
  created_repo: "🆕 Created {URL}"
  opened_pr: "🔀 Opened PR {URL} in {REPO}"
  merged_pr: "🎉 Merged PR {URL} in {REPO}"
  opened_issue: "❗ Opened issue {URL} in {REPO}"
  released: "🚀 Released {URL} in {REPO}"
  added_member: "👥 Became collaborator on {URL}"
  reviewed_pr: "👀 Reviewed {URL} in {REPO}"
  changes_approved: "✅ Approved {URL} in {REPO}"