settings:
  username: "0bVdnt"
  max_lines: 5
  readme_file: "./README.md"
  commit_msg: "chore: update recent activity"

  disabled_events:
    - push
    - comments

messages:
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  new_release: "🚀 Released {ID} in {REPO}"
